version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "develop"
    open-pull-requests-limit: 10

    groups:
      patch-updates:
        patterns: ["*"]
        update-types: ["patch"]
      minor-updates:
        patterns: ["*"]
        update-types: ["minor"]
      next-major:
        patterns: ["next"]
        update-types: ["major"]

    commit-message:
      prefix: "ðŸ”§ deps"
      include: "scope"

    labels:
      - "dependencies"
      - "automated"
      - "automerge"

    rebase-strategy: "auto"

    allow:
      - dependency-type: "production"
      - dependency-type: "development"

    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
